# Generated by Django 3.2.9 on 2022-02-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('archive_id', models.IntegerField(primary_key=True, serialize=False)),
                ('archive_url', models.CharField(max_length=300)),
                ('frequency', models.CharField(max_length=100)),
                ('entry_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('source_link', models.CharField(max_length=300)),
                ('map_area', models.CharField(max_length=100)),
                ('map_scale', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('archive_id_array', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
