# Generated by Django 3.2.9 on 2022-02-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0002_auto_20220201_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author_name',
            new_name='author_list',
        ),
        migrations.AddField(
            model_name='entry',
            name='article_title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
