# Generated by Django 3.2.9 on 2022-02-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0003_auto_20220221_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='map_area',
        ),
        migrations.AddField(
            model_name='archive',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapone_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='planet',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='planet_flag',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
