# Generated by Django 3.2.9 on 2022-02-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0004_auto_20220221_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='planet',
            new_name='planet_name',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='region',
            new_name='region_name',
        ),
    ]
