# Generated by Django 3.2.9 on 2022-02-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0005_auto_20220222_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='map_scale',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
