# Generated by Django 3.2.9 on 2022-02-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0006_alter_entry_map_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='archive_id_array',
        ),
    ]
