# Generated by Django 3.2.9 on 2022-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0007_remove_user_archive_id_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='archive_url',
        ),
        migrations.AddField(
            model_name='archive',
            name='keyword',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
