# Generated by Django 3.2.9 on 2022-02-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0008_auto_20220222_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='planet_flag',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='planet_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='region_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='map_body',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='publication_date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
