# Generated by Django 3.2.9 on 2022-03-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0010_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
