# Generated by Django 3.2.9 on 2022-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0011_remove_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
