# Generated by Django 3.2.9 on 2022-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapone_api', '0012_alter_entry_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
